from __future__ import annotations

from pathlib import Path
from typing import List, Optional, Tuple

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import pydeck as pdk
import streamlit as st


# ============================================================
# 0. Page Configuration
# ============================================================

st.set_page_config(
    page_title="NYC Airbnb Hidden Gem Finder",
    page_icon="🏙️",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# 1. Project Paths
# ============================================================

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR

MODEL_TABLE_PATH = PROJECT_ROOT / "data" / "processed" / "nyc_airbnb_undervalued_model_table.csv"
CANDIDATE_PATH = PROJECT_ROOT / "outputs" / "undervalued_candidates.csv"
CLUSTER_SUMMARY_PATH = PROJECT_ROOT / "outputs" / "undervalued_cluster_summary.csv"
MODEL_COMPARISON_PATH = PROJECT_ROOT / "outputs" / "model_comparison.csv"


# ============================================================
# 2. Helper Functions
# ============================================================

def require_columns(df: pd.DataFrame, cols: List[str]) -> List[str]:
    """Return the columns that exist in the dataframe."""
    return [c for c in cols if c in df.columns]


def safe_numeric(series: pd.Series) -> pd.Series:
    """Convert a column to numeric while keeping invalid values as NaN."""
    return pd.to_numeric(series, errors="coerce")


def money(x: float) -> str:
    """Format numeric value as US dollar text."""
    if pd.isna(x):
        return "N/A"
    return f"${x:,.0f}"


def pct(x: float) -> str:
    """Format decimal or percentage-like number."""
    if pd.isna(x):
        return "N/A"
    return f"{x:.1f}%"


def normalize_score(s: pd.Series, higher_is_better: bool = True) -> pd.Series:
    """
    Min-max normalize a numeric series into [0, 1].
    If all values are identical or missing, return 0.5.
    """
    s = pd.to_numeric(s, errors="coerce")
    if s.notna().sum() == 0:
        return pd.Series(0.5, index=s.index)

    lo, hi = s.min(), s.max()
    if np.isclose(lo, hi):
        return pd.Series(0.5, index=s.index)

    score = (s - lo) / (hi - lo)
    if not higher_is_better:
        score = 1 - score
    return score.fillna(0.5)


@st.cache_data(show_spinner=False)
def load_data() -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Load model output tables generated by the previous project pipeline.

    Expected main table:
    data/processed/nyc_airbnb_undervalued_model_table.csv

    Expected optional outputs:
    outputs/undervalued_candidates.csv
    outputs/undervalued_cluster_summary.csv
    outputs/model_comparison.csv
    """
    if not MODEL_TABLE_PATH.exists():
        st.error(
            "Missing model output table. Please run:\n\n"
            "`python src/04_price_prediction.py`\n"
            "`python src/05_undervalued_clustering.py`\n\n"
            f"Expected file: `{MODEL_TABLE_PATH}`"
        )
        st.stop()

    df = pd.read_csv(MODEL_TABLE_PATH, low_memory=False)

    candidates = pd.read_csv(CANDIDATE_PATH, low_memory=False) if CANDIDATE_PATH.exists() else pd.DataFrame()
    cluster_summary = (
        pd.read_csv(CLUSTER_SUMMARY_PATH, low_memory=False)
        if CLUSTER_SUMMARY_PATH.exists()
        else pd.DataFrame()
    )
    model_comparison = (
        pd.read_csv(MODEL_COMPARISON_PATH, low_memory=False)
        if MODEL_COMPARISON_PATH.exists()
        else pd.DataFrame()
    )

    return df, candidates, cluster_summary, model_comparison


def prepare_dashboard_data(df: pd.DataFrame) -> pd.DataFrame:
    """
    Add dashboard-friendly fields:
    - discount_pct: predicted-vs-actual discount percentage
    - recommendation_score: weighted ranking score for top deals
    - display_name: clean listing label
    """
    df = df.copy()

    numeric_cols = [
        "effective_price",
        "predicted_price",
        "price_gap",
        "undervaluation_ratio",
        "review_scores_rating",
        "number_of_reviews",
        "reviews_in_window",
        "distance_to_nearest_subway_km",
        "crime_intensity_log_1000m",
        "latitude",
        "longitude",
        "calendar_available_rate",
        "calendar_price_volatility",
        "weekend_price_premium",
    ]

    for col in numeric_cols:
        if col in df.columns:
            df[col] = safe_numeric(df[col])

    if "predicted_price" in df.columns and "effective_price" in df.columns:
        df["discount_pct"] = np.where(
            df["predicted_price"] > 0,
            100 * (df["predicted_price"] - df["effective_price"]) / df["predicted_price"],
            np.nan,
        )
        df["discount_pct"] = df["discount_pct"].clip(lower=0)
    else:
        df["discount_pct"] = np.nan

    # Review evidence combines lifetime reviews and study-window reviews.
    if "number_of_reviews" in df.columns:
        review_base = df["number_of_reviews"].fillna(0)
    else:
        review_base = pd.Series(0, index=df.index)

    if "reviews_in_window" in df.columns:
        review_base = review_base + 2 * df["reviews_in_window"].fillna(0)

    df["review_evidence_score_raw"] = np.log1p(review_base)

    # Rating score: use 4.0 as a reasonable lower anchor for high-quality listings.
    if "review_scores_rating" in df.columns:
        df["rating_score_raw"] = df["review_scores_rating"].fillna(df["review_scores_rating"].median())
    else:
        df["rating_score_raw"] = 4.5

    # Transit score: shorter distance to subway is better.
    if "distance_to_nearest_subway_km" in df.columns:
        df["transit_score_raw"] = df["distance_to_nearest_subway_km"]
    else:
        df["transit_score_raw"] = np.nan

    # Final recommendation score.
    # The score is intentionally interpretable:
    #   45% price discount,
    #   25% rating quality,
    #   15% review reliability,
    #   10% subway accessibility,
    #   5% lower reported-crime intensity context.
    discount_component = normalize_score(df["discount_pct"], higher_is_better=True)
    rating_component = normalize_score(df["rating_score_raw"], higher_is_better=True)
    review_component = normalize_score(df["review_evidence_score_raw"], higher_is_better=True)
    transit_component = normalize_score(df["transit_score_raw"], higher_is_better=False)

    if "crime_intensity_log_1000m" in df.columns:
        crime_component = normalize_score(df["crime_intensity_log_1000m"], higher_is_better=False)
    else:
        crime_component = pd.Series(0.5, index=df.index)

    df["recommendation_score"] = (
        45 * discount_component
        + 25 * rating_component
        + 15 * review_component
        + 10 * transit_component
        + 5 * crime_component
    )

    if "name" in df.columns:
        df["display_name"] = df["name"].fillna("Unnamed listing").astype(str).str.slice(0, 80)
    elif "id" in df.columns:
        df["display_name"] = "Listing " + df["id"].astype(str)
    else:
        df["display_name"] = "Airbnb listing"

    return df


def sidebar_filters(df: pd.DataFrame) -> pd.DataFrame:
    """Create sidebar filters and return filtered dataframe."""
    st.sidebar.header("🔎 Search Filters")

    filtered = df.copy()

    if "neighbourhood_group_cleansed" in filtered.columns:
        boroughs = sorted(filtered["neighbourhood_group_cleansed"].dropna().astype(str).unique())
        selected_boroughs = st.sidebar.multiselect(
            "Borough",
            options=boroughs,
            default=boroughs,
        )
        filtered = filtered[filtered["neighbourhood_group_cleansed"].astype(str).isin(selected_boroughs)]

    if "room_type" in filtered.columns:
        room_types = sorted(filtered["room_type"].dropna().astype(str).unique())
        selected_room_types = st.sidebar.multiselect(
            "Room Type",
            options=room_types,
            default=room_types,
        )
        filtered = filtered[filtered["room_type"].astype(str).isin(selected_room_types)]

    if "effective_price" in filtered.columns:
        max_price_available = int(np.nanpercentile(filtered["effective_price"], 95)) if filtered["effective_price"].notna().any() else 1000
        max_price = st.sidebar.slider(
            "Maximum Observed Price",
            min_value=0,
            max_value=max(100, max_price_available),
            value=max(100, max_price_available),
            step=25,
        )
        filtered = filtered[filtered["effective_price"].fillna(np.inf) <= max_price]

    min_rating = st.sidebar.slider(
        "Minimum Rating",
        min_value=0.0,
        max_value=5.0,
        value=4.5,
        step=0.1,
    )
    if "review_scores_rating" in filtered.columns:
        filtered = filtered[filtered["review_scores_rating"].fillna(0) >= min_rating]

    min_discount = st.sidebar.slider(
        "Minimum Model-Implied Discount",
        min_value=0,
        max_value=90,
        value=10,
        step=5,
        help="Discount = (predicted price - observed price) / predicted price.",
    )
    filtered = filtered[filtered["discount_pct"].fillna(0) >= min_discount]

    min_reviews = st.sidebar.slider(
        "Minimum Review Evidence",
        min_value=0,
        max_value=100,
        value=5,
        step=1,
        help="Uses lifetime number_of_reviews when available.",
    )
    if "number_of_reviews" in filtered.columns:
        filtered = filtered[filtered["number_of_reviews"].fillna(0) >= min_reviews]

    only_candidates = st.sidebar.checkbox(
        "Show only model-flagged undervalued candidates",
        value=False,
    )
    if only_candidates and "undervalued_candidate" in filtered.columns:
        filtered = filtered[filtered["undervalued_candidate"].fillna(0).astype(int) == 1]

    if "undervalued_cluster" in filtered.columns and filtered["undervalued_cluster"].notna().any():
        cluster_values = sorted(
            filtered["undervalued_cluster"]
            .dropna()
            .astype(int)
            .unique()
            .tolist()
        )
        selected_clusters = st.sidebar.multiselect(
            "Spatial Cluster ID",
            options=cluster_values,
            default=cluster_values,
        )
        filtered = filtered[
            filtered["undervalued_cluster"].isna()
            | filtered["undervalued_cluster"].astype("Int64").isin(selected_clusters)
        ]

    st.sidebar.markdown("---")
    st.sidebar.caption(
        "Tip: For a live presentation, start with all listings, then turn on "
        "'model-flagged candidates' to show how the model narrows the market."
    )

    return filtered


def metric_card(label: str, value: str, help_text: Optional[str] = None) -> None:
    """Wrapper for metric display."""
    st.metric(label=label, value=value, help=help_text)


def render_overview(df: pd.DataFrame, filtered: pd.DataFrame, model_comparison: pd.DataFrame) -> None:
    """Render top-level project summary."""
    st.subheader("1. Market Overview and Model Output")

    c1, c2, c3, c4, c5 = st.columns(5)

    with c1:
        metric_card("Listings Shown", f"{len(filtered):,}")
    with c2:
        if "undervalued_candidate" in filtered.columns:
            n_candidates = int(filtered["undervalued_candidate"].fillna(0).sum())
            metric_card("Flagged Deals", f"{n_candidates:,}")
        else:
            metric_card("Flagged Deals", "N/A")
    with c3:
        metric_card(
            "Median Observed Price",
            money(filtered["effective_price"].median()) if "effective_price" in filtered.columns else "N/A",
        )
    with c4:
        metric_card(
            "Median Predicted Price",
            money(filtered["predicted_price"].median()) if "predicted_price" in filtered.columns else "N/A",
        )
    with c5:
        metric_card(
            "Median Discount",
            pct(filtered["discount_pct"].median()) if "discount_pct" in filtered.columns else "N/A",
            help_text="Median model-implied discount among filtered listings.",
        )

    if not model_comparison.empty:
        st.markdown("#### Model Comparison")
        display_cols = require_columns(model_comparison, ["model", "MAE", "RMSE", "R2"])
        st.dataframe(
            model_comparison[display_cols].style.format(
                {
                    "MAE": "{:.4f}",
                    "RMSE": "{:.4f}",
                    "R2": "{:.4f}",
                }
            ),
            use_container_width=True,
            hide_index=True,
        )


def render_map(filtered: pd.DataFrame) -> None:
    """Render interactive map of listings."""
    st.subheader("2. Interactive Spatial Map")

    map_cols = require_columns(
        filtered,
        [
            "latitude",
            "longitude",
            "display_name",
            "neighbourhood_group_cleansed",
            "neighbourhood_cleansed",
            "room_type",
            "effective_price",
            "predicted_price",
            "price_gap",
            "discount_pct",
            "recommendation_score",
            "review_scores_rating",
            "undervalued_candidate",
            "undervalued_cluster",
        ],
    )

    if "latitude" not in map_cols or "longitude" not in map_cols:
        st.warning("Latitude and longitude are required for the map.")
        return

    map_df = filtered[map_cols].dropna(subset=["latitude", "longitude"]).copy()

    if map_df.empty:
        st.warning("No listings available after filtering.")
        return

    # Limit map points for smoother interaction.
    map_df = map_df.sort_values("recommendation_score", ascending=False).head(3000)

    midpoint = [map_df["latitude"].mean(), map_df["longitude"].mean()]

    map_df["candidate_color"] = np.where(
        map_df.get("undervalued_candidate", 0).fillna(0).astype(int) == 1,
        255,
        90,
    )

    layer = pdk.Layer(
        "ScatterplotLayer",
        data=map_df,
        get_position="[longitude, latitude]",
        get_radius=65,
        get_fill_color="[candidate_color, 110, 80, 150]",
        pickable=True,
        auto_highlight=True,
    )

    tooltip = {
        "html": """
        <b>{display_name}</b><br/>
        Borough: {neighbourhood_group_cleansed}<br/>
        Neighborhood: {neighbourhood_cleansed}<br/>
        Room type: {room_type}<br/>
        Observed price: ${effective_price}<br/>
        Predicted price: ${predicted_price}<br/>
        Discount: {discount_pct}%<br/>
        Rating: {review_scores_rating}<br/>
        Score: {recommendation_score}
        """,
        "style": {"backgroundColor": "white", "color": "black"},
    }

    view_state = pdk.ViewState(
        latitude=midpoint[0],
        longitude=midpoint[1],
        zoom=10,
        pitch=0,
    )

    st.pydeck_chart(
        pdk.Deck(
            layers=[layer],
            initial_view_state=view_state,
            tooltip=tooltip,
            map_style="light",
        ),
        use_container_width=True,
    )

    st.caption(
        "Darker highlighted points represent stronger deal candidates under the model-based ranking. "
        "The map supports the story that undervalued opportunities are spatially uneven across NYC."
    )


def render_recommendations(filtered: pd.DataFrame) -> None:
    """Render ranked recommendation table and listing detail panel."""
    st.subheader("3. Hidden Gem Recommendation Engine")

    if filtered.empty:
        st.warning("No listings match the current filters.")
        return

    ranking_cols = require_columns(
        filtered,
        [
            "id",
            "display_name",
            "neighbourhood_group_cleansed",
            "neighbourhood_cleansed",
            "room_type",
            "effective_price",
            "predicted_price",
            "price_gap",
            "discount_pct",
            "review_scores_rating",
            "number_of_reviews",
            "reviews_in_window",
            "distance_to_nearest_subway_km",
            "crime_intensity_log_1000m",
            "undervaluation_ratio",
            "recommendation_score",
            "undervalued_candidate",
            "undervalued_cluster",
        ],
    )

    top_n = st.slider("Number of top recommendations", 5, 50, 15, step=5)

    ranked = (
        filtered[ranking_cols]
        .sort_values(["recommendation_score", "discount_pct"], ascending=False)
        .head(top_n)
        .copy()
    )

    rename_map = {
        "display_name": "Listing",
        "neighbourhood_group_cleansed": "Borough",
        "neighbourhood_cleansed": "Neighborhood",
        "room_type": "Room Type",
        "effective_price": "Observed Price",
        "predicted_price": "Predicted Price",
        "price_gap": "Price Gap",
        "discount_pct": "Discount %",
        "review_scores_rating": "Rating",
        "number_of_reviews": "Reviews",
        "reviews_in_window": "Recent Reviews",
        "distance_to_nearest_subway_km": "Subway Distance km",
        "crime_intensity_log_1000m": "Crime Intensity log",
        "undervaluation_ratio": "Predicted / Actual",
        "recommendation_score": "Recommendation Score",
        "undervalued_candidate": "Model Flag",
        "undervalued_cluster": "Cluster",
    }

    display = ranked.rename(columns=rename_map)

    format_dict = {
        "Observed Price": "${:,.0f}",
        "Predicted Price": "${:,.0f}",
        "Price Gap": "${:,.0f}",
        "Discount %": "{:.1f}",
        "Rating": "{:.2f}",
        "Subway Distance km": "{:.2f}",
        "Crime Intensity log": "{:.2f}",
        "Predicted / Actual": "{:.2f}",
        "Recommendation Score": "{:.1f}",
    }

    st.dataframe(
        display.style.format({k: v for k, v in format_dict.items() if k in display.columns}),
        use_container_width=True,
        hide_index=True,
    )

    st.markdown("#### Listing Detail Explorer")

    if "id" in ranked.columns:
        options = ranked["id"].astype(str).tolist()
        selected_id = st.selectbox("Select a listing ID", options=options)
        selected = filtered[filtered["id"].astype(str) == selected_id].iloc[0]
    else:
        selected_idx = st.selectbox("Select a listing row", options=ranked.index.tolist())
        selected = filtered.loc[selected_idx]

    d1, d2, d3, d4 = st.columns(4)

    with d1:
        st.metric("Observed Price", money(selected.get("effective_price", np.nan)))
    with d2:
        st.metric("Predicted Market Price", money(selected.get("predicted_price", np.nan)))
    with d3:
        st.metric("Estimated Saving", money(selected.get("price_gap", np.nan)))
    with d4:
        st.metric("Recommendation Score", f"{selected.get('recommendation_score', np.nan):.1f}")

    st.write(
        f"**Listing:** {selected.get('display_name', 'Unknown listing')}  \n"
        f"**Neighborhood:** {selected.get('neighbourhood_cleansed', 'Unknown')}, "
        f"{selected.get('neighbourhood_group_cleansed', 'Unknown')}  \n"
        f"**Room Type:** {selected.get('room_type', 'Unknown')}  \n"
        f"**Rating:** {selected.get('review_scores_rating', np.nan):.2f}  \n"
        f"**Subway Distance:** {selected.get('distance_to_nearest_subway_km', np.nan):.2f} km"
    )


def render_charts(filtered: pd.DataFrame) -> None:
    """Render analytical charts that support interpretation."""
    st.subheader("4. Key Insights")

    if filtered.empty:
        st.warning("No data available for charts after filtering.")
        return

    c1, c2 = st.columns(2)

    with c1:
        if "neighbourhood_group_cleansed" in filtered.columns and "discount_pct" in filtered.columns:
            borough_discount = (
                filtered.groupby("neighbourhood_group_cleansed", as_index=False)
                .agg(
                    median_discount=("discount_pct", "median"),
                    median_price=("effective_price", "median"),
                    listings=("discount_pct", "size"),
                )
                .sort_values("median_discount", ascending=False)
            )

            fig = px.bar(
                borough_discount,
                x="neighbourhood_group_cleansed",
                y="median_discount",
                hover_data=["median_price", "listings"],
                title="Median Model-Implied Discount by Borough",
                labels={
                    "neighbourhood_group_cleansed": "Borough",
                    "median_discount": "Median Discount (%)",
                    "median_price": "Median Observed Price",
                    "listings": "Listings",
                },
            )
            st.plotly_chart(fig, use_container_width=True)

    with c2:
        if "effective_price" in filtered.columns and "predicted_price" in filtered.columns:
            sample_df = filtered.sample(min(len(filtered), 3000), random_state=42)

            fig = px.scatter(
                sample_df,
                x="effective_price",
                y="predicted_price",
                color="undervalued_candidate" if "undervalued_candidate" in sample_df.columns else None,
                hover_name="display_name",
                hover_data=require_columns(
                    sample_df,
                    [
                        "neighbourhood_cleansed",
                        "room_type",
                        "discount_pct",
                        "review_scores_rating",
                    ],
                ),
                title="Observed Price vs. Predicted Market Price",
                labels={
                    "effective_price": "Observed Effective Price",
                    "predicted_price": "Predicted Market Price",
                    "undervalued_candidate": "Model Flag",
                },
            )

            max_axis = np.nanpercentile(
                pd.concat([sample_df["effective_price"], sample_df["predicted_price"]]),
                98,
            )
            fig.add_trace(
                go.Scatter(
                    x=[0, max_axis],
                    y=[0, max_axis],
                    mode="lines",
                    name="Observed = Predicted",
                    line=dict(dash="dash"),
                )
            )
            fig.update_xaxes(range=[0, max_axis])
            fig.update_yaxes(range=[0, max_axis])
            st.plotly_chart(fig, use_container_width=True)

    c3, c4 = st.columns(2)

    with c3:
        if "room_type" in filtered.columns and "effective_price" in filtered.columns:
            fig = px.box(
                filtered,
                x="room_type",
                y="effective_price",
                points=False,
                title="Observed Price Distribution by Room Type",
                labels={
                    "room_type": "Room Type",
                    "effective_price": "Observed Effective Price",
                },
            )
            fig.update_yaxes(range=[0, np.nanpercentile(filtered["effective_price"], 95)])
            st.plotly_chart(fig, use_container_width=True)

    with c4:
        if "distance_to_nearest_subway_km" in filtered.columns and "discount_pct" in filtered.columns:
            sample_df = filtered.sample(min(len(filtered), 3000), random_state=42)
            fig = px.scatter(
                sample_df,
                x="distance_to_nearest_subway_km",
                y="discount_pct",
                color="neighbourhood_group_cleansed" if "neighbourhood_group_cleansed" in sample_df.columns else None,
                hover_name="display_name",
                title="Discount Opportunity vs. Subway Accessibility",
                labels={
                    "distance_to_nearest_subway_km": "Distance to Nearest Subway km",
                    "discount_pct": "Model-Implied Discount (%)",
                    "neighbourhood_group_cleansed": "Borough",
                },
            )
            st.plotly_chart(fig, use_container_width=True)


def render_cluster_analysis(cluster_summary: pd.DataFrame) -> None:
    """Render undervalued spatial cluster summary."""
    st.subheader("5. Spatial Cluster Summary")

    if cluster_summary.empty:
        st.info(
            "No cluster summary file was found. "
            "Run `python src/05_undervalued_clustering.py` to generate cluster-level outputs."
        )
        return

    st.write(
        "The clustering step groups nearby undervalued listings into spatial opportunity zones. "
        "This helps convert individual recommendations into neighborhood-level market insights."
    )

    display_cols = require_columns(
        cluster_summary,
        [
            "cluster_id",
            "number_of_listings",
            "median_effective_price",
            "median_predicted_price",
            "median_undervaluation_ratio",
            "median_rating",
            "most_common_neighbourhoods",
            "median_subway_distance",
            "median_crime_intensity",
        ],
    )

    st.dataframe(
        cluster_summary[display_cols].style.format(
            {
                "median_effective_price": "${:,.0f}",
                "median_predicted_price": "${:,.0f}",
                "median_undervaluation_ratio": "{:.2f}",
                "median_rating": "{:.2f}",
                "median_subway_distance": "{:.2f}",
                "median_crime_intensity": "{:.2f}",
            }
        ),
        use_container_width=True,
        hide_index=True,
    )

    if "number_of_listings" in cluster_summary.columns and "cluster_id" in cluster_summary.columns:
        fig = px.bar(
            cluster_summary.sort_values("number_of_listings", ascending=False).head(15),
            x="cluster_id",
            y="number_of_listings",
            hover_data=require_columns(
                cluster_summary,
                [
                    "most_common_neighbourhoods",
                    "median_effective_price",
                    "median_predicted_price",
                    "median_undervaluation_ratio",
                ],
            ),
            title="Largest Undervalued Listing Clusters",
            labels={
                "cluster_id": "Cluster ID",
                "number_of_listings": "Number of Listings",
            },
        )
        st.plotly_chart(fig, use_container_width=True)


def render_workflow_explanation() -> None:
    """Render non-technical explanation for presentation use."""
    st.subheader("6. How the Dashboard Connects to the Data Science Workflow")

    st.markdown(
        """
        **Step 1 — Data Integration.**  
        The project combines Airbnb listing attributes, calendar-based pricing behavior,
        review activity, subway accessibility, and reported-crime context into one listing-level table.

        **Step 2 — Price Prediction.**  
        A supervised regression model estimates each listing's theoretical market price using
        listing, host, review, temporal, and spatial features.

        **Step 3 — Residual-Based Deal Detection.**  
        A listing is treated as potentially undervalued when its predicted market price is
        meaningfully higher than its observed effective price, while also maintaining strong
        review quality and enough review evidence.

        **Step 4 — Spatial Opportunity Analysis.**  
        The dashboard maps these listings and summarizes spatial clusters, turning model output
        into an interpretable recommendation tool.

        **Step 5 — User-Facing Product.**  
        Instead of only reporting model metrics, this app allows users to dynamically filter
        listings by price, rating, borough, room type, subway distance, and model-implied discount.
        """
    )


# ============================================================
# 3. Main App
# ============================================================

def main() -> None:
    raw_df, candidates, cluster_summary, model_comparison = load_data()
    df = prepare_dashboard_data(raw_df)

    st.title("🏙️ NYC Airbnb Hidden Gem Finder")
    st.caption(
        "An interactive dashboard for discovering undervalued Airbnb listings in New York City "
        "using model-predicted market price, review quality, spatial accessibility, and neighborhood context."
    )

    with st.expander("What does this app do?", expanded=True):
        st.write(
            "This app turns the project pipeline into a user-facing recommendation product. "
            "It compares each listing's observed effective price with its model-predicted market price, "
            "then ranks listings by price discount, rating quality, review evidence, subway accessibility, "
            "and neighborhood context. The goal is not just to predict price, but to help users identify "
            "potential high-value Airbnb opportunities."
        )

    filtered = sidebar_filters(df)

    tabs = st.tabs(
        [
            "Overview",
            "Map",
            "Recommendations",
            "Insights",
            "Clusters",
            "Workflow",
        ]
    )

    with tabs[0]:
        render_overview(df, filtered, model_comparison)

    with tabs[1]:
        render_map(filtered)

    with tabs[2]:
        render_recommendations(filtered)

    with tabs[3]:
        render_charts(filtered)

    with tabs[4]:
        render_cluster_analysis(cluster_summary)

    with tabs[5]:
        render_workflow_explanation()

    st.markdown("---")
    st.caption(
        "Dashboard designed as an optional project enhancement. "
        "Model-implied undervaluation should be interpreted as a decision-support signal, "
        "not as a guaranteed market outcome."
    )


if __name__ == "__main__":
    main()